# Generated by Django 2.1.3 on 2018-11-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(default=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=False, max_length=270, null=True)),
                ('parent_id', models.IntegerField(default=False, null=True)),
                ('code', models.CharField(default=False, max_length=30, null=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
    ]
